### ISSUE TITLE
Block Visibility not an option

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms-blocks#142]
### Reproduction Steps

+ Hop in a form
+ click a default block to add visibility setting
+ or add a image block and try to add visibility settings

### Expected Behavior

+ you can make an image or other block hide based on visibility settings

### Actual Behavior

+ alas you cannot the setting has disappeared in the depths

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: https://natalie-test-site.myliftersite.com
Site Url: https://natalie-test-site.myliftersite.com
Login Url: https://natalie-test-site.myliftersite.com/wp-login.php
Version: 5.8.1
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Not Set
Permalink Structure: /%postname%/
Show On Front: posts
Wp Cron: Yes


Settings
-------------------------------------------

Version: 5.4.0
Db Version: 5.4.0
Course Catalog: Course Catalog (#35) [https://natalie-test-site.myliftersite.com/courses/]
Membership Catalog: Membership Catalog (#36) [https://natalie-test-site.myliftersite.com/memberships/]
Student Dashboard: Dashboard (#38) [https://natalie-test-site.myliftersite.com/dashboard/]
Checkout Page: Purchase (#37) [https://natalie-test-site.myliftersite.com/purchase/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: no
Password Strength Meter: no
Minimum Password Strength: 
Terms Required: no
Terms Page: Not Set
Checkout Names: 
Checkout Address: 
Checkout Phone: 
Checkout Email Confirmation: no
Open Registration: yes
Registration Names: 
Registration Address: 
Registration Phone: 
Registration Voucher: 
Registration Email Confirmation: no
Account Names: 
Account Address: 
Account Phone: 
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: team+sandbox@lifterlms.com
Email From Name: A LifterLMS Sandbox
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Stripe: Enabled
Stripe Test Mode: Enabled
Stripe Logging: no
Stripe Order: 1
Manual: Disabled
Manual Logging: 
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.35
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 5000
Php Max Upload Size: 512 MB
Php Memory Limit: 256M
Php Post Max Size: 1024M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 7.3.31
Software: Apache/2.4.51 (Unix) OpenSSL/1.1.1
Wp Memory Limit: 256M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36


Theme
-------------------------------------------

Name: Astra
Version: 3.7.3
Themeuri: https://wpastra.com/
Authoruri: https://wpastra.com/about/
Template: 
Child Theme: No
Llms Support: Yes


Plugins
-------------------------------------------

Elementor: 3.4.6
Elementor Pro: 3.3.8
LifterLMS: 5.4.0
LifterLMS Custom Fields: 2.0.2
LifterLMS Stripe Payment Gateway: 5.3.2
Manage User Columns: 1.0.3
User Switching: 1.5.8


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------




```

</details>

### This issue has been recreated:

+ [x] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

### Related User Information

this was found based on a ticket but the user wasn't complaining about this issue or even noticed it and I don't think cares.

**Comment by thomasplevy** [comment]
@nrherron92 

Block visibility is *intentionally* disabled for registration and account edit forms.

Block visibility is enabled on checkout forms for *most* blocks, with some exception. The settings on required blocks (like email/password) have their options reduced in order to ensure users don't accidentally break their forms. These can be displayed to *either everyone* or *logged out users only*. 

Also note that visibility cascades up on certain blocks when confirmation fields are used. You can't require email address confirmation for only certain types of users. So you can't make confirmation visible conditionally. You have to make the whole group conditionally visible. The visibilty settings are found on the *confirmation group* block, not on the individual fields.

The registration form is only *ever displayed* to logged out users, so using logic to determine block visibility based on enrollment or other factors *doesn't make any sense*. All fields are always displayed. 

The account edit form can only ever be displayed to logged in users so the reverse is true. As I type this I realize that there may be some value in changing this behavior. Perhaps the account form should allow conditional visibility based on enrollment (but not on logged in status). I could see disabling visibility for the required fields (email, password, display name) and then making all the other blocks have visibility enabled but removing the option for "logged out" users. This would allow only showing a field specific to Membership A to users enrolled in membership A. I'd accept this as a feature enhancement in favor of a bug report.

**Comment by eri-trabiccolo** [comment]
@thomasplevy this is my fault I inducted Natalie into opening this issue, while we were troubleshooting something else.
We were actually working on a registration form so we didn't pay attention on the fact it was actually a specific form.
I'd say we can close this if @nrherron92 agrees.

**Comment by nrherron92** [comment]
@thomasplevy i think where i saw this as an issue was the custom forms more so. Like if you create a custom form and want certain things to show to users of membership A compared to membership B. but I do agree it is more of a feature request in that regard. 

but yes a. this it totally rocco's fault and b. we can close this and add as a feature request :P

**Comment by thomasplevy** [comment]
@nrherron92 

> i think where i saw this as an issue was the custom forms more so. Like if you create a custom form and want certain things to show to users of membership A compared to membership B. but I do agree it is more of a feature request in that regard.

Let's be clear though -- what kind of a form is this? If these are *Checkout* forms then they can already do this and if you're seeing an issue with a *CHECKOUT* form then we have a bug that we need to investigate further on this user's site.

If you're talking about registration forms, the logic *simply does not make sense* because the reg form is only ever shown to a logged out user. So enrollment visibility settings cannot make any logical sense.

If you're talking about account edit forms then, yes, this could be a feature request to allow visibility customization on certain fields.

**Comment by nrherron92** [comment]
@thomasplevy Ah okay gotcha gotcha! 

I was confusing myself looking at registration with custom fields enabled but not actually looking at a new form or the checkout form but yeah nevermind then!

**Comment by thomasplevy** [comment]
Closing in favor of #143 (feature request / enhancement)
