### ISSUE TITLE
Block visibility settings do not apply to Classic (editor) block

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms-blocks#41]
### 1. Reproduction Steps

+ Create a course with a Classic (editor) block
+ set the Classic block Enrollment Visibility to 'logged in users'
+ save
+ visit the course as logged out user (or refresh the editor page)

### 2. Expected Behavior

+ I'd expect to not see the classic block content not displayed
(after refreshing the editor page if you check that setting you can see your change has been not saved)

### 3. Actual Behavior

+ classic block content was displayed

### 4. Error Messages / Logs

n/a

### 5. System Report

n/a

### 6. Browser, Device, and Operating System

n/a

### Considerations
If I look at the course content with the code editor I can see that the classic block doesn't look like the other blocks, it's not wrapped into something like:
```
<!-- wp:classic {"llms_visibility_in":"this"} -->
<p>classic content</p>
<!-- /wp:classic -->
```
(or something of the sort)
as I would expected, but it's just:
```
<p>classic content</p>
```
so, of course, there's no place where to save the visibility attribute. I guess we should just disable the Block visibility settings for the classic block.

**Comment by thomasplevy** [comment]
Since classic is more of a migration tool (for the WP core) than anything, we can just disable visibility on these blocks (as you've suggested).

If users need to use visibility they should convert the classic block to blocks and then add visibility to the new blocks. If that's arduous (because there could be a tremendous number of blocks) they can create a block group and apply the visibility to the entire group.

**Comment by thomasplevy** [comment]
This is why it doesn't render the attributes: https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/classic/save.js
