### ISSUE TITLE
LifterLMS Block Enrollment Visibility does not save with Atomic Blocks or Vdo Cipher

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms-blocks#45]
### Reproduction Steps

+ Install Atomic Blocks ~~(or Vdo Cipher)~~
+ Add an AB Block to a course.
+ Set the restriction to anything but the default and save.
+ Refresh the page.

### Expected Behavior

+ The restriction settings would be saved and applied to the block on the front end.

### Actual Behavior

+ The settings get reset to the default

HS-117815 (Atomic Blocks)
~~HS-117906 (VdoCipher -- he hasn't actually given us access to his site but I confirmed locally)~~ See #53

**Comment by thomasplevy** [comment]
Looks like this isn't working for Atomic Blocks because of the load order of assets. I'm experimenting with loading our assets earlier the default and as of this moment I don't see any side effects but I'm going to hold for a bit for committing to this as a fix in case there are other consequences I'm not anticipating.

**Comment by thomasplevy** [comment]
Moving VDOCipher to a new issue (becuaes while they're both enrollment visibility it's a completely different underlying issue and I don't want us confused in conversation about them)

**Comment by thomasplevy** [comment]
Resolved by https://github.com/gocodebox/lifterlms-blocks/commit/c0b13ab188788c6c98276a4c6ce76bad06540256
