### ISSUE TITLE
Limit block visibility to a selected Course (or Membership) breaks the block itself

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms-blocks#94]
### Reproduction Steps

+ Edit a Course
+ Select a block (not the continue button),  and limit it's visibility as per the screenshot below:

![Schermata 2021-05-05 alle 20 00 36](https://user-images.githubusercontent.com/7689242/117188013-d8677000-addc-11eb-837c-e4a05ebff252.png)

### Expected Behavior

+ The block visibility should be limited as selected

### Actual Behavior

+ The block breaks in the editor:
![Schermata 2021-05-05 alle 20 05 00](https://user-images.githubusercontent.com/7689242/117188804-c0442080-addd-11eb-9f26-dd2be6818428.png)

You can change whatever setting, it will still be broken UNTIL you remove the selected course.

Note:
Switching to the code editor you'll see that we store the whole post resource in the `llms_visibility_posts` attribute, while I guess we should only store the post ids(?). 

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

```

Lifterlms Blocks at https://github.com/gocodebox/lifterlms-blocks/commit/9957f17d0cd28ad1a2277bb45bd3c779791a0738
```

### This issue has been recreated:
+ [x] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by thomasplevy** [comment]
@eri-trabiccolo I didn't expect the above commit to actually fix this but it did. I think maybe the issue was the *size* of the request?

In any event, after looking around it seems to be that the only information we *truly need* to store on the block is the ID, post title, and post type. I've reduced this in https://github.com/gocodebox/lifterlms-blocks/commit/acd31dd049245ed558de6e5d3d3859c116985c5f

And that seems to have fixed this issue. 

I added a filter to so that if, for some reason, someone needs a property that we've now excluded it can be added through the filter.

This is a technically backwards incompatible change (I guess?) we're storing less data than we used to. I can't imagine anything actually being affected by this but it is maybe something important to note. That said, the next release is 2.0.0 so it's "safe" to make that kind of change here.

Do you see any issue with this implementation?

**Comment by eri-trabiccolo** [comment]
@thomasplevy yeah I think the size could've been the issue, yes.
But have we really always stored all that stuff? If so, why it started breaking only now?!

Ok for the filter.

I don't see any issue with this implementation. It was pretty much my idea too. We could actually even only store the ids, then when rendering the 'selected' we can make a rest request to retrieve the post title and type.... Don't we do something similar in the custom-fields modal (posts associated to the checkout form)?!

**Comment by thomasplevy** [comment]
> But have we really always stored all that stuff? If so, why it started breaking only now?!

I think changes to the search components caused this. I think.

> We could actually even only store the ids, then when rendering the 'selected' we can make a rest request to retrieve the post title and type.... Don't we do something similar in the custom-fields modal (posts associated to the checkout form)?!

Mmmm, yes, but there's a lot of rewriting to do here. Let's save that as a future optimization. I think this is good for now.
